//
// This file is generated by data_server_js/routes/./toTypescript.pl MedusaDataService Medusa/medusa-routes.js Medusa
//

import { Injectable, Injector } from '@angular/core';
import { DataService } from "./data.service"

@Injectable()
export class MedusaDataService extends DataService{

	constructor( injector: Injector ) { 
		super(injector);
	}

	// //
	// // Get Methods
	// //
	Get_Measure(measure_id:number=null) {
		let user = null;
		user = this._userService.name();
		let cmd = "Medusa/Measure";
		if (user != null) {
			cmd = cmd + "/" + user;
		}
		if (measure_id != null) {
			cmd = cmd + "/" + measure_id;
		}
		return this.get(cmd);
	}

	Get_Measure_Group() {
		let user = this._userService.name();
		let cmd = "Medusa/Measure/Group";
		cmd = cmd + "/" + user;
		return this.get(cmd);
	}

	// Get_Results(query_id:number=null) {
	// 	let user = null;
	// 	user = this._userService.name();
	// 	let cmd = "Medusa/Result";
	// 	if (user != null) {
	// 		cmd = cmd + "/" + user;
	// 	}
	// 	if (query_id != null) {
	// 		cmd = cmd + "/" + query_id;
	// 	}
	// 	return this.get(cmd);
	// }



	// //
	// // Put Methods
	// //
	// //
	// // Post Methods
	// //
	// //
	// // Delete Methods
	// //
}
