//
// This file is generated by data_server_js/routes/./toTypescript.pl SegmentDataService Segment/segment-routes.js Segment
//

import { Injectable, Injector } from '@angular/core';
import { DataService } from "./data.service"

@Injectable()
export class SegmentDataService extends DataService{

	constructor( injector: Injector ) { 
		super(injector);
	}

	//
	// Get Methods
	//
	Get_Header(object_type_id:number=null, header_id:number=null) {
		let user = null;
		user = this._userService.name();
		let cmd = "Segment/Header";
		if (user != null) {
			cmd = cmd + "/" + user;
		}
		if (object_type_id != null) {
			cmd = cmd + "/" + object_type_id;
		}
		if (header_id != null) {
			cmd = cmd + "/" + header_id;
		}
		return this.get(cmd);
	}

	Get_Header_Value(header_id:number=null, header_value_id:number=null) {
		let user = null;
		user = this._userService.name();
		let cmd = "Segment/Header/Value";
		if (user != null) {
			cmd = cmd + "/" + user;
		}
		if (header_id != null) {
			cmd = cmd + "/" + header_id;
		}
		if (header_value_id != null) {
			cmd = cmd + "/" + header_value_id;
		}
		return this.get(cmd);
	}

	Get_Object_Type(segment_id:number=null, object_type_id:number=null) {
		let user = null;
		user = this._userService.name();
		let cmd = "Segment/Object_Type";
		if (user != null) {
			cmd = cmd + "/" + user;
		}
		if (segment_id != null) {
			cmd = cmd + "/" + segment_id;
		}
		if (object_type_id != null) {
			cmd = cmd + "/" + object_type_id;
		}
		return this.get(cmd);
	}

	//
	// Put Methods
	//
	//
	// Post Methods
	//
	//
	// Delete Methods
	//
}
